betagouv/portail-rse

- impact/metabase/management/commands/sync_metabase.py
pour correspondre au nom actuel du service
> Remplacement du terme impact

- impact/public/templates/public/index.html
de « Impact » vers « Portail RSE »
> suppression du bandeau annonçant le renommage du service

- impact/reglementations/templates/reglementations/fiches/csrd.html
- impact/reglementations/templates/reglementations/fiches/dispositif-alerte.html
Met à jour les seuils d'application de la CSRD et ajoute la section "Sanctions" à la fiche Dispositif d'Alerte, ainsi que les textes de référence associés
> Correction fiches mars2024

- impact/reglementations/templates/reglementations/fiches/audit-energetique.html
J'ai ajouté le mot énergétique.
> Wording : ajout du mot énergétique

- impact/reglementations/templates/reglementations/fiches/bdese.html
- impact/reglementations/templates/reglementations/fiches/bilan-ges.html
- impact/reglementations/templates/reglementations/fiches/csrd.html
- impact/reglementations/templates/reglementations/fiches/dispositif-alerte.html
- impact/reglementations/templates/reglementations/fiches/dispositif-anticorruption.html
- impact/reglementations/templates/reglementations/fiches/dpef.html
- impact/reglementations/templates/reglementations/fiches/index-egalite-professionnelle.html
- impact/reglementations/templates/reglementations/fiches/plan-vigilance.html
ajout de points, point-virgules, espaces insécables, etc.
> fix: corrections typographiques sur les réglementations

- impact/reglementations/templates/reglementations/fiches/audit-energetique.html
Clauclau complètement dingo se lance dans le dark web
> Correction fiche réglementaire audit énergétique

- front/src/lib/SearchEntreprise.svelte
l'entreprise doit exister préalablement dans la base de données
> permet le rattachement à une entreprise fictive de test

- impact/reglementations/templates/reglementations/fiches/index-egalite-professionnelle.html
https://trello.com/c/X9wLPEmN/319-modifier-le-lien-du-site-vers-egapro
Modifie le lien pointé par le bouton « en savoir plus » de la réglementation Egalité Professionnelle.
> Modification du lien en savoir plus vers une URL plus adaptée

- Pipfile
- Pipfile.lock
voir :
https://www.djangoproject.com/weblog/2024/sep/03/security-releases/
> Maj sécurité Django 4.2.16

- impact/templates/base.html
Complément de  #144
(en fait, c'est plutôt le front qui produisait du volume)
> fix: modification de l'échantillonage Sentry pour le front

- Pipfile
- Pipfile.lock
- impact/reglementations/forms/csrd.py
- impact/reglementations/models/csrd.py
- impact/reglementations/templates/fragments/esrs.html
- impact/reglementations/templates/fragments/telechargement_xlsx.html
- impact/reglementations/templates/reglementations/espace_csrd/phase1_etape2_1.html
- impact/reglementations/tests/test_csrd_views.py
- impact/reglementations/urls.py
- impact/reglementations/views/csrd.py
- impact/static/scss/styles.scss
Possibilité de télécharger un fichier xlsx des enjeux sélectionnés.
cf. https://trello.com/c/lvp4PO1x/36-us-08-r%C3%A9cup%C3%A9rer-la-liste-de-mes-enjeux-s%C3%A9lectionn%C3%A9s
> Liste d'enjeux xlsx

- impact/reglementations/models/csrd.py
- **fix: commentaires sur un N+1 lors de la création des enjeux réglementés**
- **Renforcement des conditions de création des enjeux**
> Amélioration de la création des enjeux

- impact/api/tests/test_recherche_entreprises.py
- impact/api/tests/test_sirene.py
La DINUM a changé d'effectif donc les tests étaient à mettre à jour.
> fix: correction de tests fonctionnels pour les API

- impact/reglementations/templates/reglementations/csrd/etape-introduction.html
- impact/reglementations/templates/reglementations/csrd/etape-selection-enjeux.html
L'identifiant d'étape étant incorrect, une 404 était affichée.
> fix: correction du chemin pour valider une étape

- impact/entreprises/forms.py
- impact/entreprises/models.py
- impact/entreprises/templates/entreprises/index.html
- impact/entreprises/templates/entreprises/qualification.html
- impact/entreprises/tests/conftest.py
- impact/entreprises/tests/test_forms.py
- impact/entreprises/tests/test_models.py
- impact/entreprises/tests/test_views.py
- impact/entreprises/views.py
- impact/public/views.py
On demande la vérification du code APE / NAF dans le formulaire de
saisie de l'entreprise.
> APE: mise à jour du formulaire de saisie

- Pipfile
- Pipfile.lock
voir :
https://www.djangoproject.com/weblog/2024/dec/04/security-releases/
> libs: MaJ vers Django 4.2.17

- impact/impact/settings.py
- impact/reglementations/templates/reglementations/csrd/etape-analyse-materialite.html
- impact/reglementations/templates/reglementations/csrd/etape-collection-donnees-entreprise.html
- impact/utils/context_processors.py
- **fix: ajout de l'URL de base de sites-faciles dans les settings Django**
- **fix: ajout de l'URL de sites-faciles dans le context-processor**
- **fix: correction des liens d'informations de l'espace CSRD**
> Correction des liens de l'espace CSRD

- impact/reglementations/templates/fragments/esrs_materiels.html
- impact/reglementations/templates/fragments/telechargement_xlsx.html
- impact/reglementations/templates/reglementations/csrd/etape-analyse-materialite.html
- impact/reglementations/templates/reglementations/csrd/etape-collection-donnees-entreprise.html
- impact/reglementations/templates/reglementations/csrd/etape-introduction.html
- impact/reglementations/templates/reglementations/csrd/etape-redaction-rapport-durabilite.html
- impact/reglementations/templates/reglementations/csrd/etape-selection-enjeux.html
- impact/reglementations/templates/snippets/gestion_csrd_menu.html
- impact/reglementations/tests/conftest.py
- impact/reglementations/tests/test_csrd_reglementation.py
- impact/reglementations/views/csrd.py
https://trello.com/c/xaf0phJ0/362-unifier-le-wording-csrd-sur-le-portail
> Unifier le wording des étapes fonctionnelles de la CSRD

- impact/entreprises/tests/test_views.py
- impact/impact/settings.py
- impact/reglementations/tests/test_reglementations.py
- impact/reglementations/urls.py
- impact/reglementations/views/__init__.py
- impact/templates/base.html
> Ajout d'une URL /tableau-de-bord utilisable dans le site vitrine

- impact/reglementations/tests/test_csrd_views.py
- impact/reglementations/views/csrd.py
- Retrait d'onglets inutiles pour fichiers à télécharger (enjeux non-matériels)
- Correction / ré-implémentation de l'onglet non-matériel
> fix: onglets ESRS présents dans les fichiers d'ADM

- impact/reglementations/tests/test_csrd_views.py
Modification des tests pour prendre en compte les modifications de #355 (oubli de commit de ma part)
> fix: modification des tests pour les ADM avec enjeux non-matériels

- Pipfile
- Pipfile.lock
MAJ sécurité : https://www.djangoproject.com/weblog/2025/mar/06/security-releases/
> fix: Màj de Django : v5.1.7

- impact/reglementations/views/csrd/analyse_ia.py
- impact/reglementations/views/csrd/csrd.py
suppression du prefixe « _ » signifiant que la fonction est privée au module.
> refacto: renommage d'une fonction qui est publique

- impact/reglementations/admin.py
- impact/reglementations/models/csrd.py
- impact/reglementations/tests/tests_csrd/test_csrd_models.py
sur un document analysé par l'IA
> admin: affichage du nombre de phrases pertinentes

- impact/reglementations/models/csrd.py
- impact/reglementations/tests/tests_csrd/test_csrd_models.py
> fix: existence possible de plusieurs rapports de durabilité officiels pour des années différentes

- impact/reglementations/tests/tests_csrd/test_analyse_ia_views.py
- impact/reglementations/views/csrd/analyse_ia.py
… les rapports CSRD officiels
rend l'envoi d'email non bloquant
> fix: gère l'envoi de l'email de notification de fin d'analyse IA pour

- impact/vsme/templates/etapes/module-complet.html
> fix: typo dans le template du module complet

- impact/vsme/tests.py
avec une version de black récente
> guillemets possibles dans les f-strings

- impact/habilitations/admin.py
Permet d'accélerer le chargement de la partie "utilisateurs" de l'admin 
---
- **fix: passage de certains champs liés en `raw_id`**
- **fix(admin): modification de l'inline habilitation**
> Amélioration de l'inline Habilitation (2)

- impact/reglementations/views/bdese.py
en cas de présence d'anciennes BDESE personnelles
> fix: erreur possible lors de la création d'une BDESE

- impact/reglementations/tests/test_reglementations.py
- impact/reglementations/tests/test_tableau_de_bord.py
- impact/reglementations/urls.py
- impact/reglementations/views/__init__.py
pour pouvoir faire des liens de communication plus ciblés (campagnes marketing, etc.)
> feat: ajoute aussi des urls génériques sur les sous pages du tableau de bord
