betagouv/portail-rse

Pipfile, Pipfile.lock
La version 6.6.0 est compatible avec Django 5.0.
=> mise-à-jour de la dépendance à whitenoise

.env.example, impact/public/tests/tests.py, impact/users/tests/test_forms.py, impact/users/tests/test_views.py
Les adresses @example.com sont bien réservées par l'IANA mais la RFC 2606 (Reserved Top Level DNS Names) indique des TLD dédiés aux besoins de test et d'exemple.
https://datatracker.ietf.org/doc/html/rfc2606
=> fausses adresses e-mail conformes à la RFC 2606

impact/api/recherche_entreprises.py, impact/api/tests/test_recherche_entreprises.py
Les mainteneurs de l'API recherche-entreprises souhaitent mieux connaitre l'origine des requêtes (cf. https://github.com/betagouv/portail-rse/issues/90).
=> ajout d'un paramètre mtm_campaign pour recherche-entreprises

impact/api/ratios_financiers.py, impact/api/tests/test_ratios_financiers.py
des erreurs 500 et 502 sont survenues depuis hier
elles provoquaient une exception JSONDecodeError dans notre code
=> fix: gère les erreurs 5XX de l'API externe ratios financiers

.github/workflows/test.yml
L'API Sirene n'est pas fiable est provoque des erreurs non significatives. Les tests réseau sont désactivés pour contourner ce problème.
=> désactivation des tests réseau dans l'intégration continue

impact/public/tests/test_simulation.py, impact/public/views.py, impact/reglementations/tests/test_bdese_reglementation.py, impact/reglementations/tests/test_bges_reglementation.py, impact/reglementations/tests/test_index_egapro_reglementation.py, impact/reglementations/views/base.py
La page du tableau de bord faisait de nombreux appels identiques à la base de données pour calculer le statut de chaque réglementation car ce calcul vérifiait l'habilitation de l'utilisateur à accéder à cette information.
En supprimant cette vérification au niveau du calcul du statut et donc en déplaçant cette responsabilité à la vue (qui faisait déjà cette vérification), on simplifie le code et on résout le problème de performance.
Issue sentry liée : 108474
=> résout un problème de performance d'appels à la base de donnée

Pipfile, Pipfile.lock
En remplacement de `psycopg2`.
Plus rapide, fonctionne mieux en synchrone et async, et gère mieux mémoire et transactions.
Potentiellement un bon candidat pour résoudre certains problèmes de mémoire vus dans [cette carte Trello](https://trello.com/c/YUcmK0vD/247-surveiller-la-consommation-m%C3%A9moire-ram) 
quelques benchmarks :
- https://www.timescale.com/blog/psycopg2-vs-psycopg3-performance-benchmark/
- https://www.spherex.dev/psycopg-2-vs-psycopg3/
- par l'auteur : https://www.varrazzo.com/blog/2020/05/19/a-trip-into-optimisation/
=> Maj vers psycopg(3)

impact/impact/settings.py
relatif à : https://trello.com/c/cGmNFxHm/106-homologuer-le-service
Ces points sont mentionnés pour correction dans le rapport d'audit d'intrusion. 
Les paramètres de session ont été modifiés pour :
- fixer la durée de session à 2 heures max.,
- ne pouvoir utiliser les cookies que dans un contexte securisé (HTTPS),
- forcer l'expiration de session à la fermeture du navigateur.
A valider ultériereurement et commenté dans le code :
- fixer la valeur de `SameSite` à `Strict` pour éviter de diffuser les cookies à des sites tiers.
=> Modification des paramètres de session

Pipfile, Pipfile.lock, impact/impact/admin_urls.py, impact/impact/hosts.py, impact/impact/settings.py, impact/impact/urls.py
Relatif à : https://trello.com/c/cGmNFxHm/106-homologuer-le-service
Le site d'admin de Django est séparé du site du Portail RSE suite à recommandation de l'audit de sécurité : 
- installation de [`django-hosts`](https://github.com/jazzband/django-hosts),
- le nom du site d'admin peut être configuré via la variable d'environnement `ADMIN_CNAME` (par défaut : `admin`),
- ne pas oublier de modifier `ALLOWED_HOSTS` pour y inclure l'URL du site d'admin.
Si possible, intégrer cette PR *avant* la PR de CSP (#131) pour pouvoir effectuer les ajustements.
Pour tester en local / dev, ajouter une résolution du nom du site d'admin. 
Par exemple, sous Linux, en ajoutant une ligne dans `/etc/hosts`  : 
```bash 
127.0.0.1 admin # ou autre
``
=> Séparation des domaines du site et de l'admin Django

impact/entreprises/tests/test_views.py
sqlite peut convertir nativement des chaînes de caractères en date,
postgresql pas aussi facilement.
La CI sous sqlite peut être trompeuse.
=> Correction d'un test cassé sous postgresql

front/src/lib/SeeMoreOrLess.svelte
L'absence de paramètre à la fonction `void()` provoque une erreur "Uncaught SyntaxError: expected expression, got ')'" non bloquante.
Cela provoque aussi l'envoi d'un rapport CSP.
=> fix: suppression d'un warning javascript

Pipfile, Pipfile.lock, cron.json, impact/users/management/commands/import_utilisateurs_brevo.py, impact/users/tests/test_commands.py
Le besoin est de faciliter le déploiement :
https://trello.com/c/DMr2JyHF/261-recenser-les-contacts-des-inscrits-non-activ%C3%A9s-sur-brevo
Les requêtes vers Brevo pour ajouter ou supprimer des e-mails sont faites avec la bibliothèque [sib-api-v3-sdk](https://pypi.org/project/sib-api-v3-sdk/) fournie par Brevo.
Créer les attributs suivants sur les contacts Brevo :
- PORTAIL_RSE_ID (type entier)
- PORTAIL_RSE_DATE_INSCRIPTION (type date)
- EMAIL_CONFIRME (type booléen)
- ENTREPRISES_NON_QUALIFIEES (type chaine)
Créer une liste spécifique aux contacts du portail-rse si elle n'existe pas.
Ces prérequis sont à faire avant le passage en recette et production.
L'attribut PORTAIL_RSE_ID permet de différencier les utilisateurs existants sur portail-rse des autres contacts existants sur Brevo (car …
=> Synchronisation des e-mails des utilisateurs dans Brevo

impact/impact/settings.py, impact/reglementations/forms/csrd.py, impact/reglementations/models/csrd.py, impact/reglementations/templates/fragments/creation_enjeu.html, impact/reglementations/templates/fragments/esrs.html, impact/reglementations/templates/fragments/selection_enjeux.html, impact/reglementations/templates/reglementations/espace_csrd/phase1_etape2_1.html, impact/reglementations/templates/snippets/modal_ESRS/enjeu_widget.html, impact/reglementations/templates/widgets/enjeu_option.html, impact/reglementations/views/fragments/enjeux.py, impact/reglementations/views/fragments/urls.py, impact/static/scss/styles.scss, impact/utils/htmx.py, impact/utils/middlewares.py
Ajout de la création d'enjeux personnalisés dans l'espace CSRD.
Un utilisateur peut ajouter et supprimer des enjeux (titre et description) dans la partie sélection des enjeux 
- création d'un enjeu 
- liste des enjeux
=> Espace CSRD : création d'enjeux

impact/reglementations/models/__init__.py, impact/reglementations/models/bdse.py, impact/reglementations/models/index_egapro.py
Les deux fonctions sont déplacées dans leur propre fichier. Cela reste transparent pour le reste du code.
=> refacto: déplacement de fonctions dédiées à egapro

impact/templates/base.html
Les scripts Matomo n'ont remonté aucune erreur durant la phase de test des CSP en mode `report-only`.
Contrairement aux autres éléments et scripts qui généraient des erreurs (Sentry et console), Matomo échouait à "bas-bruit".
Le problème peut apparemment être résolu en suivant ces instructions: https://matomo.org/faq/general/faq_20904/ .. ce qui est exactement ce que nous avons fait (`nonce`).
Par contre en modifiant légèrement le script inclus dans Matomo (voir https://developer.matomo.org/guides/tracking-javascript-guide), tout semble fonctionner correctement sur l'environnement de recette.
On retrouve désormais les appels de `trackview` vers Matomo en mode CSP (absents auparavant) :
=> Adaptation des scripts Matomo pour la CSP

impact/impact/admin_urls.py
Lors d'une erreur 404, 403 ou 500, le site d'admin (virtuel) essaye
d'utiliser la gestion d'erreur du site principal.
Dans ce cas, de nombreux éléments ne sont pas définis dans les templates
et on obtient de nombreuses erreurs (redirections infinies) un peu
cryptiques dans Sentry.
=> Ajout d'une gestion d'erreurs minimale pour le site d'admin

impact/impact/settings.py, impact/static/js/lang/tarteaucitron.fr.js, impact/static/js/tarteaucitron.js, impact/static/js/tarteaucitron.matomo.service.js, impact/static/js/tarteaucitron.services.js, impact/static/scss/dsfr-theme-tac.scss, impact/templates/base.html
Permet d'activer ou non certains services utilisant des cookies pour le tracking.
Dans notre cas, uniquement Matomo, qui ne peut pas être désactivé complètement (tracking de vues sans cookies).
Par contre, la désactivation bloque le fonctionnement des _heatmaps_.
=> Cookies et consentement utilisateur (tarteaucitron)

impact/static/js/tarteaucitron.matomo.service.js
Les pages vues sont trackées quoi qu'il advienne (régression)
=> Correction du consentement Matomo

impact/habilitations/models.py, impact/users/forms.py, impact/users/tests/test_views.py
Des utilisateurs signalent l'incapacité de créer un compte sans que ce soit bien compris de notre côté.
En contrôlant mieux la longueur acceptée pour les fonctions exercées dans l'entreprise, cela permettra peut-être d'aiguiller les utilisateurs, et sinon d'éliminer l'hypothèse que ce soit cela le problème.
=> limitation de la longueur des fonctions exercées dans une entreprise

impact/public/templates/public/index.html, impact/templates/base.html
Avec la séparation du site en deux : le versant vitrine fait avec sites-faciles et le code métier qui reste dans le dépôt portail-rse, il est nécessaire de pointer certaines pages vers le site vitrine.
=> Separation sites faciles

impact/impact/settings.py, impact/templates/base.html, impact/utils/context_processors.py
Une variable d'environnement facultative permet de choisir sur quel domaine les cookies de tarteaucitron s'appliquent. Cela permet en production de les mettre sur l'ensemble du domaine portail-rse et donc qu'ils soient valides sur le service sites-facile ainsi que le service de ce dépôt (app.portail...).
=> Paramétrage du domaine sur lequel les cookies s'appliquent

.github/workflows/test.yml, Pipfile, Pipfile.lock
- Django 5.1.4 : nouvelle version majeure
- Python 3.12.8 : version la plus haute de la branche 3.12 gérée
actuellement par Scalingo
À passer en recette d'abord pour voir si tout se passe bien ...
=> chore(libs): MàJ versions de Python et Django

impact/entreprises/forms.py
Corrige le message « SyntaxWarning: invalid escape sequence '\d' ».
=> fix: suppression d'un warning sur une chaîne incorrecte

impact/templates/base.html
voir : https://trello.com/c/6td4uEdS/354-corriger-lerreur-%C3%A0-la-d%C3%A9connexion
Django 5 ne permet pas d'utiliser la vue de déconnexion avec une méthode `GET`
=> fix: correction de la déconnexion (Django 5)

Pipfile, Pipfile.lock
Voir :  https://www.djangoproject.com/weblog/2025/jan/14/security-releases/
=> chore(deps): MaJ vers Django 5.1.5

impact/templates/base.html
Prise en compte de la correction pour Django 5, pour des petits écrans où le bouton de déconnexion est dans un autre menu.
Cela complète [la correction principale](https://github.com/betagouv/portail-rse/pull/224) pour les utilisateurs sur mobile.
=> fix: correction de la déconnexion pour mobile

impact/templates/base.html
Le but est de faciliter la navigation entre les deux services (vitrine et gestion).
=> remplacement de lien vers un lien externe

impact/public/templates/public/index.html
Le bloc principal n'était plus centré, avec le bouton d'action seul sur une seconde colonne.
On a eu deux retours utilisateurs à ce propos
=> fix: correction du rendu sur écran large

impact/public/templatetags/absolute_url.py, impact/public/tests/tests.py, impact/public/urls.py, impact/public/views.py, impact/templates/base.html, impact/templates/snippets/boutons_menu.html
Le besoin est d'avoir les liens du menu sur le site vitrine identique à celui de l'app django.
Pour cela, les liens sont servis sur une nouvelle route, que le site vitrine devra requêter pour obtenir le HTML à insérer dans la page.
=> Disponibilité des liens du menu sur une URL

Pipfile, Pipfile.lock, impact/impact/settings.py
Cela permet au menu d'être récupéré en javascript et donc remplacer l'ancien menu.
cf. https://trello.com/c/Al8NdDub/355-unifier-les-boutons-du-menu
La PR limite l'autorisation au site vitrine plutôt que `*`. Il sera toujours possible d'élargir plus tard si on a une API par exemple.
=> Ajout du site vitrine dans les autorisations CORS

impact/impact/settings.py
nécessaire pour que les cookies de sesssion soient acceptés par le serveur lorsque le site vitrine fait la requête de récupération du menu
=> ajout de l'en-tête access-control-allow-credentials

impact/impact/settings.py
La déconnexion sur le site vitrine nécessite cette en-tête car elle est faite par HTMX.
=> Ajout d'une en-tête pour accepter les requêtes HTMX

impact/templates/snippets/boutons_menu.html, impact/users/tests/test_views.py, impact/users/urls.py, impact/users/views.py
Le passage de django 4 à django 5 a obligé à passer d'une déconnexion GET à POST. Cependant, la réutilisation du bloc menu sur le site vitrine provoque des erreurs dû à un manque d'autorisation CORS et CSRF.
Malgré des tentatives répétées pour ajouter la configuration adéquate pour autoriser cette requête par HTMX ou un POST basique, la requête est refusée. En repassant sur un simple lien, donc réalisé en GET, ce type de problème disparait. Cela permet de se déconnecter depuis le site vitrine.
=> Changement du mode de déconnexion (vers GET)

.github/workflows/test.yml
Apparement, la configuration de la CI nécessite de préciser la même
version de Python que celle du `Pipfile`.
Si la version de la CI est plus récente que celle définie pour le
projet, l'installation des dépendances ne s'effectue pas correctement et
la CI échoue.
=> fix: correction de la version de python dans la CI

impact/reglementations/models/csrd.py, impact/reglementations/tests/test_csrd_views.py
Voir : https://trello.com/c/xxZE6tQp/368-passer-la-s%C3%A9lection-des-enjeux-%C3%A0-s%C3%A9lectionn%C3%A9-par-d%C3%A9faut
Tous les enjeux sont sélectionnés par défaut lors de la création d'un
rapport CSRD.
_note_ : 
les anciens rapports CSRD gardent pour l'instant l'ancien
comportement. 
A voir si une migration de données est nécessaire : à confirmer côté métier.
=> feat: sélection par défaut des enjeux

impact/templates/snippets/entete_page.html
Nécessaire depuis le retour à un GET à la place d'un POST HTMX. Est cohérent avec le lien de déconnexion pour écran large.
=> fix: correction du lien de déconnexion mobile

impact/impact/settings.py, impact/reglementations/models/csrd.py, impact/reglementations/templates/fragments/esrs.html, impact/reglementations/templates/fragments/liste_enjeux_selectionnes.html, impact/reglementations/templates/reglementations/csrd/etape-selection-enjeux.html, impact/reglementations/templates/snippets/tab_maj_nombre_enjeux.html, impact/reglementations/tests/test_csrd_views.py, impact/reglementations/views/fragments/enjeux.py, impact/reglementations/views/fragments/urls.py, impact/utils/middlewares.py
Voir #290 
Permettre de voir immédiatement dans les tabs le nombre d'enjeux sélectionnés / non-sélectionnés, et d'avoir le détail pour chaque option.
=> Ajout du décompte des enjeux dans les tabs

impact/templates/base.html
GSC détecte des URLs dupliquées sur le domaine de cette application de gestion. Cela n'a pas vraiment d'importance car c'est le site vitrine dont on souhaite améliorer le référencement. Je suppose que ce sous-domaine se retrouve référencé car on fusionne les cookies des deux domaines.
Il n'est pas possible d'utiliser simplement `request.get_full_path` dans le template car, dans ce cas, les paramètres GET sont aussi affichés dans l'URL canonique. Le but de la définition de l'URL canonique est les supprimer pour que les différentes URL ne soient plus considérées comme unique mais bien comme la même page.
=> définition d'une URL canonique

docker-compose.yml
Pour Minio (S3 local), il est nécessaire d'ajouter une variable d'environnement `SCALEWAY_S3_ENDPOINT_URL` qui pointe vers le serveur local (par défaut : `http://localhost:9001/`)
=> Ajout d'un docker-compose de développement

impact/public/templatetags/absolute_url.py, impact/public/tests/test_templatetags.py
Permet d'éviter des boucles d'erreur dans les tests.
=> le tag absolute_url résiste à une Exception non gérée

impact/reglementations/tests/tests_csrd/test_csrd_views.py, impact/reglementations/views/csrd/csrd.py, impact/reglementations/views/csrd/urls.py
Cela permet d'insérer un lien sur le site vitrine permettant d'afficher l'étape analyse d'écart du rapport de durabilité sur le site de gestion.
Le comportement est similaire au tableau de bord où l'URL /tableau-de-bord permet d'arriver sur le tableau de bord de l'utilisateur grâce à des redirections.
close #461
=> Ajout d'une URL redirigeant vers l'analyse d'écart sans variable

impact/habilitations/context_processors.py, impact/habilitations/decorators.py, impact/habilitations/enums.py, impact/habilitations/models.py, impact/habilitations/tests/test_decorators.py, impact/habilitations/tests/test_user_role.py, impact/impact/settings.py, impact/reglementations/forms/csrd.py, impact/reglementations/templates/fragments/lien_rapport.html, impact/reglementations/templates/fragments/selection_enjeux.html, impact/reglementations/templates/fragments/selection_enjeux_materiels.html, impact/reglementations/templates/reglementations/csrd/etape-analyse-ecart.html, impact/reglementations/templates/snippets/csrd_submit.html, impact/reglementations/templates/widgets/enjeu_option.html, impact/reglementations/views/csrd/fragments/enjeux.py, impact/reglementations/views/csrd/fragments/enjeux_materiels.py, impact/utils/middlewares.py
A la suite de #456 et #468 
Ajout des éléments techniques pour gérer les habilitations : 
- décorateur pour les vues 
- variables de contexte pour les templates
- quelques méthodes utilitaires sur `Habilitation` et `UserRole` pour une intégration plus facile
=> feat: ajout des éléments techniques de gestion des rôles

impact/impact/settings.py
La mise-à-jour de la façon de configurer django-vite permet d'éliminer ce warning : 
> [...]/site-packages/django_vite/core/asset_loader.py:752: DeprecationWarning: The settings [DJANGO_VITE_DEV_MODE, DJANGO_VITE_DEV_SERVER_PORT, DJANGO_VITE_STATIC_URL_PREFIX, DJANGO_VITE_MANIFEST_PATH, DJANGO_VITE_ASSETS_PATH] will be removed in future releases of django-vite. Please switch to defining your settings as DJANGO_VITE = {"default": {...},}.
La constante `DJANGO_VITE_ASSETS_PATH` disparait car elle n'est plus utilisée dans la bibliothèque django-vite : 
https://github.com/MrBin99/django-vite/blob/c6df9f5ab4d3aac8481abfcca010e2faa9653554/django_vite/core/asset_loader.py#L682
=> suppression d'un warning émis par django-vite

impact/reglementations/templates/snippets/csrd_menu.html
A cause d'une modification sur un fichier de menu similaire à celui des VSME 
(qui n'avait d'ailleurs rien à faire dans la PR : on l'a loupé à la revue).
=> fix: réparation du menu de l'espace CSRD

impact/public/templates/public/index.html, impact/public/templates/public/resultats_simulation.html, impact/public/templates/public/simulation.html, impact/templates/snippets/entete_page.html, impact/users/templates/users/login.html
les mtm_campaign sont réservés pour tracker les sources externes de trafic (actions bizdev)
Permet de débloquer #563 pour la partie app
=> fix: supprime tous les mtm_campaign des liens internes de l'app

Procfile.dev
Utilisation de deux port différents :
- site sur le port par défaut (8000)
- admin django sur le 8001
=> site principal et interface admin en parallèle en local

Procfile.dev
Cela n'est plus utile car l'admin django est fourni à nouveau sur le port par défaut (8000).
=> suppression de l'admin servie sur un port dédié en local

impact/templates/snippets/entete_page.html
nécessaire car c'est le seul endroit pour atteindre la page de contact
=> retour du bouton de contact

cron.json, scripts/sync_metabase.sh
TIL: limité à 5 commandes max., au delà on doit faire appel au support
=> fix: limite du nombre de cron pour Scalingo

impact/vsme/templates/etapes/module-complet.html, impact/vsme/tests.py, impact/vsme/views.py
La commission européenne utilise le terme « module complet » donc Portail RSE fait de même.
=> vsme: remplacement du terme module narratif par module complet
